export const types = {
    ADD_SEARCH: '[PIXABAY] ADD_SEARCH',
    ADD_DATA_TO_PAGES: '[PIXABAY] ADD_DATA_TO_PAGES',
    SUBTRACT_TO_ACTUAL_PAGE: '[PIXABAY] SUBTRACT_TO_ACTUAL_PAGE',
    ADD_TO_ACTUAL_PAGE: '[PIXABAY] ADD_TO_ACTUAL_PAGE',
    RESET_ACTUAL_PAGE: '[PIXABAY] RESET_ACTUAL_PAGE',
};
